micronaut:
  application:
    name: todoGet
cassandra:
  default:
    basic:
      contact-points:
        - "127.0.0.1:9042"
      session-keyspace: todo
      load-balancing-policy:
        local-datacenter: datacenter1
nats.addresses:
  - nats://localhost:4222